// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else
      {
        return android;
      }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAJX27lmYIrp-Tlt935eADV8-JO__reLNQ",
      authDomain: "foodpower-492d1.firebaseapp.com",
      projectId: "foodpower-492d1",
      storageBucket: "foodpower-492d1.appspot.com",
      messagingSenderId: "847730903611",
      appId: "1:847730903611:web:b1750b659a588594e5ea1e",
      measurementId: "G-6WJQC0XX4W"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWYwToweQEqtkrmkMAV0JituUNtCU-MH0',
    appId: '1:847730903611:android:2f56b5225ed739d5e5ea1e',
    messagingSenderId: "847730903611",
    projectId: 'foodpower-492d1',
    storageBucket: 'foodpower-492d1.appspot.com',
    measurementId: "G-6WJQC0XX4W"
  );
}